version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - scraper

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    ports:
      - "5000:5000"
    volumes:
      - ./app/PythonScripts:/app

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=EL_P4_WebScraping_SQL
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
