version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    ports:
      - "5000:5000"
    volumes:
      - ./app/PythonScripts:/app
