FROM python:3.9

WORKDIR /app

# Copy Python script and dependencies
COPY app/PythonScripts/ .
COPY app/PythonScripts/requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose a port for communication with the Laravel application
EXPOSE 5000

CMD ["python", "-m", "http.server", "5000"]
